export interface RecordedStep {
  description: string;
  code: string;
  optional: boolean;
}

export interface SpecTokenUsage {
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
}

/**
 * Generates a Playwright .spec.ts file from a list of recorded steps.
 */
const VIEWPORT_SIZES: Record<string, { width: number; height: number }> = {
  mobile:  { width: 390,  height: 844  },
  tablet:  { width: 768,  height: 1024 },
  desktop: { width: 1280, height: 800  },
};

export function generateSpec(
  title: string,
  steps: RecordedStep[],
  sourceFile: string,
  model?: string,
  usage?: SpecTokenUsage,
  viewport?: string
): string {
  const lines: string[] = [];

  const hasAssert = steps.some(s => s.code?.includes('expect('));
  lines.push(`import { test${hasAssert ? ', expect' : ''} } from '@playwright/test'`);
  lines.push(``);
  lines.push(`// Generated by md2spec from: ${sourceFile}`);
  if (model && usage && usage.costUsd > 0) {
    lines.push(`// Model: ${model} | Tokens: ${usage.inputTokens} in + ${usage.outputTokens} out | Cost: $${usage.costUsd.toFixed(4)}`);
  }
  lines.push(``);

  // Add test.use({ viewport }) if a viewport preset is defined
  if (viewport && VIEWPORT_SIZES[viewport]) {
    const vp = VIEWPORT_SIZES[viewport];
    lines.push(`test.use({ viewport: { width: ${vp.width}, height: ${vp.height} } }) // ${viewport}`);
    lines.push(``);
  }

  lines.push(`test(${JSON.stringify(title)}, async ({ page }) => {`);

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];
    lines.push(`  // Step ${i + 1}: ${step.description}`);

    if (step.optional) {
      lines.push(`  try {`);
      for (const codeLine of step.code.split('\n')) {
        lines.push(`    ${codeLine}`);
      }
      lines.push(`  } catch { /* optional step */ }`);
    } else {
      lines.push(`  ${step.code}`);
    }

    if (i < steps.length - 1) {
      lines.push(``);
    }
  }

  lines.push(`})`);
  lines.push(``);

  return lines.join('\n');
}
