import { test, expect } from '@playwright/test'

// Generated by md2spec from: ancillaries-vuelo-hotel-home-desktop.md
// Model: claude-haiku-4-5 | Tokens: 10933 in + 218 out | Cost: $0.0096

test("Ancillaries Vuelo + hotel HOME (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/
  await page.goto("https://es.stayforlong.com/");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1000);
  } catch { /* consent not present */ }
  try {
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().click({ timeout: 5000 });
  } catch { /* popup not present */ }

  // Step 2: Close popup of subscription if present clicking on close icon
  try {
    // TODO: could not generate code for: Close popup of subscription if present clicking on close icon
  } catch { /* optional step */ }

  // Step 3: Click Flight + Hotel option in the top menu
  await page.getByText("Vuelo + Hotel", {"exact":true}).click();

  // Step 4: Assert that the page title is Flight + Hotel
  await expect(page.getByRole("link", {"name":"Vuelo + Hotel"})).toContainText("Vuelo + Hotel");
})
