import { test, expect } from '@playwright/test'

// Generated by md2spec from: banner-hdp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 2049 in + 73 out | Cost: $0.0019

test("Banner HDP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to HDP https://www.stayforlong.com/hotel/mx/hilton-garden-inn-cancun-airport_cancun-and-vicinity
  await page.goto("https://www.stayforlong.com/hotel/mx/hilton-garden-inn-cancun-airport_cancun-and-vicinity");

  // Step 2: Promotional banner is displayed in the bottom of the search box
  try {
    await expect(page.locator("[class*='banner'], [class*='promotional'], [class*='promo']")).toBeVisible();
  } catch { /* optional step */ }
})
