import { test, expect } from '@playwright/test'

// Generated by md2spec from: banner-serp-movil.md
// Model: claude-haiku-4-5 | Tokens: 3280 in + 54 out | Cost: $0.0028

test.use({ viewport: { width: 390, height: 844 } }) // mobile

test("Banner SERP (Movil)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/gb/city/london
  await page.goto("https://es.stayforlong.com/gb/city/london");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().click();
  } catch { /* popup not present */ }

  // Step 2: Check if the banner is displayed bottom to the photos
  try {
    await expect(page.getByTestId("billboard-banner")).toBeVisible();
  } catch { /* optional step */ }
})
