import { test } from '@playwright/test'

// Generated by md2spec from: banner-hdp-movil.md
// Model: claude-haiku-4-5 | Tokens: 2051 in + 77 out | Cost: $0.0019

test.use({ viewport: { width: 390, height: 844 } }) // mobile

test("Banner HDP (Movil)", async ({ page }) => {
  // Step 1: Navigate to https://www.stayforlong.com/hotel/mx/hilton-garden-inn-cancun-airport_cancun-and-vicinity
  await page.goto("https://www.stayforlong.com/hotel/mx/hilton-garden-inn-cancun-airport_cancun-and-vicinity");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().click();
  } catch { /* popup not present */ }

  // Step 2: Double click on text "The longer you stay, the cheaper it gets"
  // TODO: could not generate code for: Double click on text "The longer you stay, the cheaper it gets"
})
