import { test, expect } from '@playwright/test'

// Generated by md2spec from: banner-serp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 2047 in + 60 out | Cost: $0.0019

test("Banner SERP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/es/city/salou
  await page.goto("https://es.stayforlong.com/es/city/salou");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().click();
  } catch { /* popup not present */ }

  // Step 2: Check if the banner is displayed bottom to the photos
  try {
    await expect(page.locator("[class*='banner']")).toBeVisible();
  } catch { /* optional step */ }
})
