import { test } from '@playwright/test'

// Generated by md2spec from: boton-show-more-accommodation-serp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 10210 in + 270 out | Cost: $0.0092

test("Boton \"Show more accommodation\" SERP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/es/city/madrid
  await page.goto("https://es.stayforlong.com/es/city/madrid");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click Show more accommodation button
  // TODO: could not generate code for: Click Show more accommodation button

  // Step 3: Wait 5 seconds
  await page.waitForTimeout(5000);

  // Step 4: Click Show more accommodation button
  // TODO: could not generate code for: Click Show more accommodation button

  // Step 5: Wait 5 seconds
  await page.waitForTimeout(5000);

  // Step 6: Click Show more accommodation button
  // TODO: could not generate code for: Click Show more accommodation button
})
