import { test } from '@playwright/test'

// Generated by md2spec from: calendario-serp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 30971 in + 633 out | Cost: $0.0273

test("Calendario SERP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to search page https://es.stayforlong.com/gb/city/london
  await page.goto("https://es.stayforlong.com/gb/city/london");

  // Step 2: Type text in search input with "barcelona"
  await page.getByPlaceholder("¿A dónde vas a viajar?").fill("barcelona");

  // Step 3: Click to the first position in the suggestions
  await page.getByTestId("suggester-option").first().click();

  // Step 4: Click to the first input date of the calendar
  await page.getByTestId("checkin-date").click({ force: true });

  // Step 5: After to the first date field is clicked, select the right arrow to go to the next month
  await page.locator(".calendar [data-testid=\"ChevronRightIcon\"]").first().click();

  // Step 6: Click and select the right arrow to go to the next month
  await page.locator(".calendar [data-testid=\"ChevronRightIcon\"]").first().click();

  // Step 7: Click and select the right arrow to go to the next month
  await page.locator(".calendar [data-testid='ChevronRightIcon']").first().click();

  // Step 8: Click and select the right arrow to go to the next month
  await page.locator(".calendar [data-testid=\"ChevronRightIcon\"]").click();

  // Step 9: Click and select the day 4 in the first month of the calendar
  await page.locator(".calendar:first-of-type [data-testid=\"default-day\"][aria-hidden=\"false\"]").filter({ hasText: "4" }).first().click();

  // Step 10: Click and select the day 6 in the first month of the calendar
  await page.locator(".calendar:first-of-type [data-testid=\"default-day\"][aria-hidden=\"false\"]").filter({ hasText: "6" }).first().click();

  // Step 11: Click to search button
  await page.getByTestId("search-button").click();
})
