import { test } from '@playwright/test'

// Generated by md2spec from: calendario-home-desktop.md
// Model: claude-haiku-4-5 | Tokens: 34940 in + 1172 out | Cost: $0.0326

test("calendario HOME (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/
  await page.goto("https://es.stayforlong.com/");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().click();
  } catch { /* popup not present */ }

  // Step 2: Close exclusive offers popup
  try {
    // TODO: could not generate code for: Close exclusive offers popup
  } catch { /* optional step */ }

  // Step 3: Enter "barcelona" in travel destination field
  await page.getByPlaceholder("Where are you going?").fill("barcelona");

  // Step 4: Select Barcelona from dropdown results
  // TODO: could not generate code for: Select Barcelona from dropdown results

  // Step 5: Click on date 13 mar
  // TODO: could not generate code for: Click on date 13 mar

  // Step 6: Navigate to next month (March 2026)
  // TODO: could not generate code for: Navigate to next month (March 2026)

  // Step 7: Navigate to next month (April 2026)
  // TODO: could not generate code for: Navigate to next month (April 2026)

  // Step 8: Navigate to next month (May 2026)
  // TODO: could not generate code for: Navigate to next month (May 2026)

  // Step 9: Navigate to next month (June 2026)
  // TODO: could not generate code for: Navigate to next month (June 2026)

  // Step 10: Navigate to next month (July 2026)
  // TODO: could not generate code for: Navigate to next month (July 2026)

  // Step 11: Navigate to next month (August 2026)
  // TODO: could not generate code for: Navigate to next month (August 2026)

  // Step 12: Navigate to next month (September 2026)
  await page.goto("https://www.booking.com");

  // Step 13: Select day 1 from calendar
  await page.locator(".calendar:first-of-type [data-testid=\"default-day\"][aria-hidden=\"false\"]").filter({ hasText: "1" }).first().click();

  // Step 14: Select day 2 from calendar
  await page.locator(".calendar:first-of-type [data-testid=\"default-day\"][aria-hidden=\"false\"]").filter({ hasText: "2" }).first().click();

  // Step 15: Click Buscar search button
  await page.getByRole("button", {"name":"Search"}).click();
})
