import { test } from '@playwright/test'

// Generated by md2spec from: calendario-home-movil.md
// Model: claude-haiku-4-5 | Tokens: 14299 in + 492 out | Cost: $0.0134

test.use({ viewport: { width: 390, height: 844 } }) // mobile

test("Calendario Home (Movil)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/?market=es&lang=es
  await page.goto("https://es.stayforlong.com/?market=es&lang=es");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().click();
  } catch { /* popup not present */ }

  // Step 2: Close exclusive offers popup
  try {
    // TODO: could not generate code for: Close exclusive offers popup
  } catch { /* optional step */ }

  // Step 3: Select check-in date 13 mar
  await page.locator("#checkinrooms").click({ force: true });

  // Step 4: Open month dropdown for March 2026
  // TODO: could not generate code for: Open month dropdown for March 2026

  // Step 5: Close month dropdown for March 2026
  // TODO: could not generate code for: Close month dropdown for March 2026

  // Step 6: Select date 19
  // TODO: could not generate code for: Select date 19

  // Step 7: Select date 23
  // TODO: could not generate code for: Select date 23

  // Step 8: Click search button
  // TODO: could not generate code for: Click search button
})
