import { test } from '@playwright/test'

// Generated by md2spec from: calendario-hdp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 27254 in + 497 out | Cost: $0.0238

test("Calendario HDP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/hotel/gb/the-ned_london
  await page.goto("https://es.stayforlong.com/hotel/gb/the-ned_london");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("button:has([data-testid=\"CloseIcon\"])").first().click();
  } catch { /* popup not present */ }

  // Step 2: Scroll down to the accomodations lista
  await page.getByTestId("rooms-list").scrollIntoViewIfNeeded();

  // Step 3: Click to the check-in field to open the date picker
  await page.locator("#checkinrooms").click({ force: true });

  // Step 4: Click the arrow to navigate to the next month
  await page.locator(".calendar [data-testid='ChevronRightIcon']").first().click();

  // Step 5: Click the arrow to navigate to the next month
  await page.locator(".calendar [data-testid=\"ChevronRightIcon\"]").first().click();

  // Step 6: Click the arrow to navigate to the next month
  await page.locator(".calendar [data-testid=\"ChevronRightIcon\"]").first().click();

  // Step 7: Select date 4 in the second month of the calendar
  await page.locator(".calendar:nth-of-type(2) [data-testid=\"default-day\"][aria-hidden=\"false\"]").filter({ hasText: "4" }).first().click();

  // Step 8: Select date 7 in the second month of the calendar
  await page.locator(".calendar:nth-of-type(2) [data-testid=\"default-day\"][aria-hidden=\"false\"]").filter({ hasText: "7" }).first().click();

  // Step 9: Wait until rooms are fully loaded
  await page.waitForTimeout(2000);
})
