import { test, expect } from '@playwright/test'

// Generated by md2spec from: cambio-de-mercado-es-it-home.md
// Model: claude-haiku-4-5 | Tokens: 13350 in + 160 out | Cost: $0.0113

test("Cambio de mercado ES, IT - HOME", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/
  await page.goto("https://es.stayforlong.com/");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click to EUR currency option in the right menu in the header
  await page.getByTestId("country-selector-button").click();

  // Step 3: Check if the popup appears with the different markets options
  try {
    try {
      await page.locator("[data-testid=\"close-button\"]").waitFor({ state: 'visible', timeout: 6000 });
      await page.locator("[data-testid=\"close-button\"]").click();
    } catch { /* popup not present */ }
  } catch { /* optional step */ }

  // Step 4: Select Italy country with EUR currency option
  await page.getByTestId("country-selector-button").click();

  // Step 5: Check if the page reloads with the new market Italy with EUR currency in the currency option on the right menu in the header
  await expect(page.getByTestId("country-selector-button")).toBeVisible();
})
