import { test } from '@playwright/test'

// Generated by md2spec from: compartir-hotel-por-x-desktop.md
// Model: claude-haiku-4-5 | Tokens: 8516 in + 128 out | Cost: $0.0073

test("Compartir hotel por X (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/hotel/es/bcn-urbaness-del-comte_barcelona
  await page.goto("https://es.stayforlong.com/hotel/es/bcn-urbaness-del-comte_barcelona");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click share icon for rating 7.9 Bien 758 comentarios
  await page.locator("button:has([data-testid=\"ShareIOSIconIcon\"])").click();

  // Step 3: Click share-link to share on X
  await page.getByTestId("share-link").filter({ hasText: "Compartir en X" }).first().click();
})
