import { test } from '@playwright/test'

// Generated by md2spec from: compartir-hotel-por-whatapp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 7738 in + 104 out | Cost: $0.0066

test("Compartir hotel por WhatApp (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/hotel/es/bcn-urbaness-del-comte_barcelona
  await page.goto("https://es.stayforlong.com/hotel/es/bcn-urbaness-del-comte_barcelona");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click to share icon
  await page.getByTestId("ShareIOSIconIcon").click();

  // Step 3: Click to "Compartir por Whatsapp" option
  await page.getByText("Compartir por Whatsapp").click();
})
