import { test } from '@playwright/test'

// Generated by md2spec from: filtros-estrellas-serp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 39448 in + 588 out | Cost: $0.0339

test("Filtros estrellas SERP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/es/city/madrid
  await page.goto("https://es.stayforlong.com/es/city/madrid");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click on rating option 1
  await page.locator("input[type='radio'][name='rating']").nth(0).click();

  // Step 3: Click on 1-star rating icon
  await page.locator("input[type='radio'][name='rating']").first().click();

  // Step 4: Click on 2-star rating checkbox
  await page.locator("input[type='radio'][name='rating']").nth(1).click();

  // Step 5: Click on 2-star rating icon
  await page.locator("input[type='radio'][name='rating']").nth(1).click();

  // Step 6: Click on 3-star rating icon
  await page.locator("input[type='radio'][name='rating']").nth(2).click();

  // Step 7: Click on 3-star rating svg
  await page.locator("input[type='radio'][name='rating']").nth(2).click();

  // Step 8: Click on 4-star rating icon
  await page.locator("input[type='radio'][name='rating']").nth(3).click();

  // Step 9: Click on 4-star rating icon again
  await page.locator("input[type='radio'][name='rating']").nth(3).click();

  // Step 10: Click on 5-star rating svg
  await page.locator("input[type='radio'][name='rating']").nth(4).click();

  // Step 11: Click on 3-star rating option
  await page.locator("input[type='radio'][name='rating']").nth(2).click();
})
