import { test } from '@playwright/test'

// Generated by md2spec from: home-mapa.md
// Model: claude-haiku-4-5 | Tokens: 17656 in + 310 out | Cost: $0.0154

test("Home & Mapa", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com
  await page.goto("https://es.stayforlong.com");

  // Step 2: Close popup of subscription if present clicking on close icon
  try {
    await page.locator("button:has([data-testid='CloseIcon'])").click();
  } catch { /* optional step */ }

  // Step 3: Enter 'madrid' in travel destination field
  await page.getByPlaceholder("¿A dónde vas a viajar?").fill("madrid");

  // Step 4: Select Madrid from dropdown suggestions
  await page.getByTestId("suggester-option").filter({ hasText: "Madrid Madrid, Comunidad de Madrid, España" }).first().click();

  // Step 5: Click search button
  await page.getByTestId("search-button").click();

  // Step 6: Click view map link
  await page.getByRole("button", {"name":"Ver mapa"}).click();
})
