import { test } from '@playwright/test'

// Generated by md2spec from: home-mapa.md
// Model: claude-haiku-4-5 | Tokens: 19746 in + 295 out | Cost: $0.0170

test("Home & Mapa", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com
  await page.goto("https://es.stayforlong.com");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Close popup of subscription if present clicking on close icon
  try {
    try {
      await page.locator("[data-testid=\"close-button\"]").waitFor({ state: 'visible', timeout: 6000 });
      await page.locator("[data-testid=\"close-button\"]").click();
    } catch { /* popup not present */ }
  } catch { /* optional step */ }

  // Step 3: Wait until the autocomplete dropdown suggestions appear
  await page.waitForTimeout(3000);

  // Step 4: Enter 'madrid' in travel destination field
  await page.getByPlaceholder("¿A dónde vas a viajar?").fill("madrid");

  // Step 5: Select Madrid from dropdown suggestions
  await page.getByText("Madrid", {"exact":false}).first().click();

  // Step 6: Click search button
  await page.getByTestId("search-button").click();

  // Step 7: Click view map link
  await page.getByRole("button", {"name":"Ver mapa"}).click();
})
