import { test } from '@playwright/test'

// Generated by md2spec from: lanzar-busqueda-con-nios-hdp-desktopo.md
// Model: claude-haiku-4-5 | Tokens: 20845 in + 291 out | Cost: $0.0178

test("Lanzar busqueda con niños HDP (Desktopo)", async ({ page }) => {
  // Step 1: Navigate to https://www.stayforlong.com/hotel/es/bcn-urbaness-del-comte_barcelon
  await page.goto("https://www.stayforlong.com/hotel/es/bcn-urbaness-del-comte_barcelon");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click on room and guest selection button
  await page.getByTestId("input-paxes").click();

  // Step 3: Click the + button to add 1 child
  await page.locator("button:has([data-testid=\"AddIcon\"])").nth(1).click();

  // Step 4: Click the age selector button to open the age dropdown
  await page.getByTestId("age-selector-btn").click();

  // Step 5: Select age 3 from the age list
  await page.locator("[class*=\"AgesList\"] li").filter({ hasText: "3" }).first().click();

  // Step 6: Click Save button
  await page.getByRole("button", {"name":"Guardar"}).click();
})
