import { test } from '@playwright/test'

// Generated by md2spec from: lanzar-busqueda-con-nio-serp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 24283 in + 330 out | Cost: $0.0207

test("Lanzar busqueda con niño SERP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://www.stayforlong.com/es/city/barcelona
  await page.goto("https://www.stayforlong.com/es/city/barcelona");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click room and guest settings button
  await page.getByRole("button", {"name":"1 Habitación · 2 adultos"}).click();

  // Step 3: Click the + button to add 1 child
  await page.locator("button:has([data-testid=\"AddIcon\"])").nth(1).click();

  // Step 4: Click the age selector button to open the age dropdown
  await page.getByTestId("age-selector-btn").click();

  // Step 5: Select age 3 from the age list
  await page.locator("#age-3").first().click();

  // Step 6: Click the Save button
  await page.getByRole("button", {"name":"Guardar"}).click();

  // Step 7: Click Search button
  await page.getByTestId("search-button").click();
})
