import { test } from '@playwright/test'

// Generated by md2spec from: logo-hdp-a-serp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 4186 in + 51 out | Cost: $0.0036

test("Logo HDP a SERP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/hotel/es/hard-rock-hotel-madrid_madrid
  await page.goto("https://es.stayforlong.com/hotel/es/hard-rock-hotel-madrid_madrid");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click on Ayuda help option
  await page.getByText("Ayuda").first().click();
})
