import { test } from '@playwright/test'

// Generated by md2spec from: logo-serp-a-home-movil.md
// Model: claude-haiku-4-5 | Tokens: 4051 in + 47 out | Cost: $0.0034

test.use({ viewport: { width: 390, height: 844 } }) // mobile

test("Logo SERP a Home (Movil)", async ({ page }) => {
  // Step 1: Navigate to https://www.stayforlong.com/es/city/madrid
  await page.goto("https://www.stayforlong.com/es/city/madrid");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click on Madrid location path
  await page.getByTestId("logo-square-brand").click();
})
