import { test } from '@playwright/test'

// Generated by md2spec from: logo-serp-a-homedesktop.md
// Model: claude-haiku-4-5 | Tokens: 3937 in + 44 out | Cost: $0.0033

test("Logo SERP a Home(Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/es/city/madrid
  await page.goto("https://es.stayforlong.com/es/city/madrid");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click on Ayuda
  await page.getByText("Ayuda").click();
})
