import { test } from '@playwright/test'

// Generated by md2spec from: mapa-desde-hdp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 8102 in + 116 out | Cost: $0.0069

test("Mapa desde HDP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/hotel/es/soho-boutique-opera_madrid
  await page.goto("https://es.stayforlong.com/hotel/es/soho-boutique-opera_madrid");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Click on "Mostrar en el mapa"
  await page.getByRole("button", {"name":"Mostrar en el mapa"}).click();

  // Step 3: Click on Filtros Precio total (€) filter
  await page.getByText("Precio total (€)").first().click();
})
