import { test } from '@playwright/test'

// Generated by md2spec from: reviews-hdp-movil.md

test.use({ viewport: { width: 390, height: 844 } }) // mobile

test("Reviews HDP (Movil)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/es/city/madrid
  await page.goto("https://es.stayforlong.com/es/city/madrid");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }
})
