import { test, expect } from '@playwright/test'

// Generated by md2spec from: visto-en-serp-desktop.md
// Model: claude-haiku-4-5 | Tokens: 8467 in + 108 out | Cost: $0.0072

test("\"Visto en\" SERP (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/hotel/es/parador-de-lleida_lleida-and-vicinity?adults=2&aid=trivago&checkIn=2026-11-19&checkOut=2026-11-20&lang=es&market=es&page=1&source=meta
  await page.goto("https://es.stayforlong.com/hotel/es/parador-de-lleida_lleida-and-vicinity?adults=2&aid=trivago&checkIn=2026-11-19&checkOut=2026-11-20&lang=es&market=es&page=1&source=meta");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Verify "Visto en" text is displayed
  await expect(page.getByText("Visto en").first()).toBeVisible();

  // Step 3: Click arrow-back-button
  await page.getByTestId("arrow-back-button").click();
})
