import { test } from '@playwright/test'

// Generated by md2spec from: WEB-XXX-qa-test-home-search-basic.md
// Model: claude-haiku-4-5 | Tokens: 42833 in + 660 out | Cost: $0.0369

test("Home search to Barcelona (Mobile)", async ({ page }) => {
  // Step 1: Navigate to https://es.stayforlong.com/
  await page.goto("https://es.stayforlong.com/");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Enter "Barcelona" in the search field
  await page.getByPlaceholder("¿A dónde vas a viajar?").fill("Barcelona");

  // Step 3: Wait until the autocomplete dropdown suggestions appear
  await page.waitForTimeout(1000);

  // Step 4: Click on the "Barcelona" option from the autocomplete dropdown suggestions
  await page.getByText("Barcelona", {"exact":false}).first().click();

  // Step 5: (Optional) Click on the check-in date field to open the calendar
  await page.getByTestId("checkin-date").click({ force: true });

  // Step 6: Click the next month arrow to navigate forward
  await page.locator(".calendar [data-testid=\"ChevronRightIcon\"]").first().click();

  // Step 7: Wait until the calendar finishes animating
  await page.waitForTimeout(500);

  // Step 8: Click the next month arrow to navigate forward
  await page.locator(".calendar [data-testid=\"ChevronRightIcon\"]").first().click();

  // Step 9: Select day 4 of the second month
  await page.locator(".calendar:nth-of-type(2) [data-testid=\"default-day\"][aria-hidden=\"false\"]").filter({ hasText: "4" }).first().click();

  // Step 10: Select day 6 of the second month
  await page.locator(".calendar:nth-of-type(2) [data-testid=\"default-day\"][aria-hidden=\"false\"]").filter({ hasText: "6" }).first().click();

  // Step 11: Click the search button
  await page.getByTestId("search-button").click();

  // Step 12: Wait until search results are loaded
  await page.waitForTimeout(5000);
})
