import { test } from '@playwright/test'

// Generated by md2spec from: WEB-YYY-qa-test-home-search-with-child-desktop.md
// Model: claude-haiku-4-5 | Tokens: 38358 in + 503 out | Cost: $0.0327

test("Lanzar búsqueda con niño HOME (Desktop)", async ({ page }) => {
  // Step 1: Navigate to https://www.stayforlong.com/?market=us&lang=en
  await page.goto("https://www.stayforlong.com/?market=us&lang=en");
  try {
    await page.locator("#adopt-accept-all-button").click({ timeout: 5000 });
    await page.waitForTimeout(1500);
  } catch { /* consent not present */ }
  try {
    await page.locator("[data-testid=\"close-button\"]").first().waitFor({ state: 'visible', timeout: 6000 });
    await page.locator("[data-testid=\"close-button\"]").first().click();
  } catch { /* popup not present */ }

  // Step 2: Type 'BARCELONA' in destination field
  await page.getByPlaceholder("Where are you travelling to?").fill("BARCELONA");

  // Step 3: Select Barcelona from search results
  await page.getByText("Barcelona").first().click();

  // Step 4: Click room and guest settings button
  await page.getByRole("button", {"name":"1 Room · 2 adults"}).click();

  // Step 5: Click the + button to add 1 child
  await page.locator("button:has([data-testid=\"AddIcon\"])").nth(1).click();

  // Step 6: Click the age selector button to open the age dropdown
  await page.getByTestId("age-selector-btn").first().click();

  // Step 7: Select age 6 from the age list
  await page.locator("#age-6").first().click();

  // Step 8: Click the Save button
  await page.getByRole("button", {"name":"Save"}).click();

  // Step 9: Click the Search button
  await page.getByTestId("search-button").click();

  // Step 10: Wait until search results are loaded
  await page.waitForTimeout(5000);
})
