import { JiraIssue, MarkdownSpec } from './types.js';
import { extractQASections } from './adfParser.js';
import { issueUrl } from './jiraClient.js';

/**
 * Converts a Jira issue key to a valid filename slug.
 * e.g. "WEB-666" → "web-666"
 */
export function toFileName(issue: JiraIssue): string {
  const key = issue.key.toLowerCase();
  const title = issue.fields.summary
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);
  return `${key}-${title}`;
}

/**
 * Converts a Jira issue to a Markdown spec.
 * Returns null if no QA section is found in the description.
 */
export function convertIssue(issue: JiraIssue, _baseUrl = ''): MarkdownSpec | null {
  const qaSection = extractQASections(issue.fields.description);

  if (!qaSection) return null;

  return {
    issueKey: issue.key,
    title: issue.fields.summary,
    sourceUrl: issueUrl(issue.key),
    qaSection,
  };
}

/**
 * Renders a MarkdownSpec to markdown string.
 */
export function renderMarkdown(spec: MarkdownSpec, baseUrl = ''): string {
  const lines: string[] = [];

  lines.push(`# ${spec.issueKey}: ${spec.title}`);
  lines.push('');
  lines.push(`<!-- Generated by jira2md from Jira issue ${spec.issueKey} -->`);
  lines.push(`<!-- Source: ${spec.sourceUrl} -->`);
  lines.push(`<!-- QA Section: ${spec.qaSection.heading} -->`);
  lines.push('');
  lines.push('## Preconditions');
  lines.push('- Browser is open and ready');
  if (baseUrl) {
    lines.push(`- Navigate to ${baseUrl}`);
  }
  lines.push('');
  lines.push('## Steps');

  spec.qaSection.steps.forEach((step, i) => {
    lines.push(`${i + 1}. ${step}`);
  });

  lines.push('');

  return lines.join('\n');
}
