import { MarkdownTest } from './types.js';

export function renderMarkdown(md: MarkdownTest): string {
  const lines: string[] = [];

  lines.push(`# ${md.title}`);
  lines.push('');
  const aiNote = md.aiEnhanced ? ` | AI-enhanced (${md.model ?? 'claude'})` : '';
  lines.push(`<!-- Generated by dd2md from Datadog Synthetics${aiNote} -->`);
  lines.push(`<!-- Source: ${md.sourceFile} -->`);
  if (md.viewport) {
    lines.push(`<!-- viewport: ${md.viewport} -->`);
  }
  lines.push('## Preconditions');
  lines.push('- Browser is open and ready');
  lines.push('');
  lines.push('## Steps');

  if (md.steps.length === 0) {
    lines.push('');
    lines.push('<!-- No steps found in source test -->');
  } else {
    md.steps.forEach((step, index) => {
      lines.push(`${index + 1}. ${step}`);
    });
  }

  lines.push('');

  return lines.join('\n');
}
